# Generated by Django 3.2.9 on 2022-05-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220507_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=452),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=3),
        ),
    ]
