# Generated by Django 3.2.8 on 2023-01-08 06:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_details', '0003_auto_20230108_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='latlng',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
