# Generated by Django 3.2.8 on 2023-01-08 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_details', '0004_orders_latlng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='latlng',
        ),
    ]
